### ISSUE TITLE
error loading module 'socket.core' from ... on x64 build

### ISSUE THREAD

**Issue by CaitSith2** [snes9x-rr/snes9x#9]
Whenever I try to run the x64 build, with lua scripts that use `local socket = require("socket")`,  the error error `loading module 'socket.core' from file '[path to snes9x x64]\socket\core.dll':
	%1 is not a valid Win32 application. ` comes up.  I have to explicitly use the x32 version to work around this issue, but I would much rather use the x64 version.

Mainly looking to use this with multibridge / emotracker,  as I run multiworld randomizers

**Comment by gocha** [comment]
I'm not sure if that's the issue of snes9x-rr or rather the one of socket module. Where did you get the x64 version of socket module?

**Comment by gocha** [comment]
I guess the problem can be solved if you replace your socket/core.dll to x64 binary.

**Comment by CaitSith2** [comment]
Actually yeah,  finding a 64bit build of socket/core.dll resolved the issue.

**Comment by TheTommynator** [comment]
I'm having the same issue. But where do I find a working 64bit build of socket/core.dll and where is the folder where I have to put it?
